display_name: Fantomask VPN

icon: ./assets/images/icon.png

keywords:
  - Fantomask VPN
  - Clash
  - ClashMeta
  - Proxy

generic_name: Fantomask VPN

categories:
  - Network

startup_notify: true

include: []